#!/usr/bin/env python3
"""AI clarification + entity-first Telegram search planner.

Clarification is generated by the LLM. The user can answer either by pressing
one of the generated inline options or simply sending a normal text message.
A dedicated "Свой ответ" button is also provided when the generated options do
not contain what the user wants.
"""
import html
import os
import secrets
import threading
import checknow_bot as bot

_pending = {}
_lock = threading.Lock()
_LANG = {"zh":"Chinese", "en":"English", "ru":"Russian", "ja":"Japanese", "ko":"Korean"}


def _languages():
    raw = os.getenv("SEARCH_LANGUAGES", "zh,en").strip()
    return [x.strip().lower() for x in raw.split(",") if x.strip().lower() in _LANG] or ["zh", "en"]


def _call(prompt, fallback):
    if not bot.LLM_API_KEY:
        return fallback
    try:
        data = bot.call_model(bot.MODELS[0], prompt)
        return data if isinstance(data, dict) else fallback
    except Exception as e:
        print(f"search AI fallback: {e}", flush=True)
        return fallback


def clarify(request):
    langs = ", ".join(_LANG[x] for x in _languages())
    prompt = f'''You are an intelligent clarification agent for a Telegram historical search.
User request: {request}
Search languages: {langs}.
Do NOT create search queries yet.

Decide whether one clarification question would materially improve THIS search.
Ask only when the request genuinely has multiple plausible interpretations, an important missing scope, or an ambiguous target. If it is already clear, return clarification_needed=false.

If clarification is needed:
- Generate EXACTLY ONE useful question from the user's request.
- Generate 2-5 concise answer options that are specific to THIS request, not generic canned choices.
- The options are suggestions, not the only possible answers.
- Do NOT include a "Свой ответ" option; the bot adds that itself.

Return strict JSON only:
{{"clarification_needed":true,"question":"...","options":[{{"label":"...","value":"..."}}]}}
or
{{"clarification_needed":false}}'''
    data = _call(prompt, {"clarification_needed": False})
    options = []
    for x in data.get("options", []):
        if isinstance(x, dict):
            label = str(x.get("label", "")).strip()[:48]
            value = str(x.get("value", "")).strip()[:300]
            if label and value:
                options.append({"label": label, "value": value})
    return {
        "clarification_needed": bool(data.get("clarification_needed")) and bool(str(data.get("question", "")).strip()) and bool(options),
        "question": str(data.get("question", "")).strip()[:700],
        "options": options[:5],
    }


def plan_search(request):
    """Generate entity-first queries without artificial Cartesian-product noise."""
    if not bot.LLM_API_KEY:
        return {"queries": [request], "intent": request}
    langs = ", ".join(_LANG[x] for x in _languages())
    prompt = f'''You are a Telegram search-query planner.
User request: {request}
Allowed languages: {langs}. If Russian is not listed, NEVER output Russian.

Extract the concrete entities/topics the user wants searched. Do not invent unrelated search intents.

RULES:
1. EVERY important named entity MUST appear ALONE first: stripe, cursor, python, tiktok, tik tok, etc.
2. Add genuine spelling variants separately, especially "tiktok" and "tik tok".
3. Add only directly useful short combinations explicitly implied by the request, such as: stripe python, cursor python, tiktok api, tik tok api, tiktok username, tik tok username, tiktok abuse, tik tok abuse.
4. Never create a Cartesian product of every entity and every modifier.
5. Do NOT invent words such as hack, exploit, bypass, attack, vulnerability, spam, flood, manipulation, injection, automation, code, script, tutorial, example, github, loop, requests, etc. unless the user explicitly asked for that concept.
6. If the user said "abuse", "abuse" is allowed. Do not turn it into ten synonyms.
7. Keep one-term entity queries; they are intentionally broad and important.
8. Search languages must be zh/en by default. Never translate the whole Russian request into search phrases.
9. Chinese queries must be natural Chinese. Keep common English brand names where appropriate.
10. Queries should normally contain 1-3 terms. No artificial maximum count: return every genuinely useful short entity/variant/combo, but do not pad.

GOOD EXAMPLE:
stripe
cursor
python
stripe python
cursor python
tiktok
tik tok
抖音
tiktok api
tik tok api
tiktok username
tik tok username
tiktok abuse
tik tok abuse

BAD EXAMPLE:
python cursor flood
python cursor attack
cursor manipulation
stripe python requests

Return strict JSON: {{"queries":[...],"intent":"..."}}'''
    data = _call(prompt, {"queries": [request], "intent": request})
    queries, seen = [], set()
    for raw in data.get("queries", []):
        q = str(raw).strip()
        if not q or len(q) > 80 or len(q.split()) > 3:
            continue
        k = q.casefold()
        if k not in seen:
            seen.add(k)
            queries.append(q)
    return {"queries": queries or [request], "intent": str(data.get("intent", request))[:1000]}


def _ask(request, plan, original):
    token = secrets.token_urlsafe(8)
    buttons, values = [], []
    for item in plan.get("options", []):
        values.append(item["value"])
        buttons.append({"text": item["label"], "callback_data": f"searchclarify:{token}:{len(values)-1}"})
    if not buttons:
        return False
    with _lock:
        _pending[token] = {
            "request": request,
            "values": values,
            "original": original,
            "chat_id": str(bot.CHAT_ID),
            "awaiting_custom": False,
        }
    rows = [buttons[i:i+2] for i in range(0, len(buttons), 2)]
    rows.append([{"text": "✏️ Свой ответ", "callback_data": f"searchclarify:{token}:custom"}])
    rows.append([{"text": "🚀 Искать без уточнения", "callback_data": f"searchclarify:{token}:skip"}])
    bot.send_message(
        "❓ <b>ИИ хочет уточнить запрос</b>\n\n"
        + html.escape(plan["question"])
        + "\n\n<i>Можно нажать вариант или просто написать свой ответ сообщением.</i>",
        bot.kb(rows),
    )
    return True


def _finish(state, extra):
    request = state["request"] + "\n\n[УТОЧНЕНИЕ ПОЛЬЗОВАТЕЛЯ]\n" + extra
    bot.answer_callback if False else None
    threading.Thread(target=state["original"], args=(request,), daemon=True).start()


def _consume_text(update):
    """Consume a normal Telegram message as a free-text clarification answer."""
    message = update.get("message") or {}
    chat_id = str((message.get("chat") or {}).get("id", ""))
    text = str(message.get("text") or "").strip()
    if not text or chat_id != str(bot.CHAT_ID) or text.startswith("/"):
        return False
    with _lock:
        token = next((k for k, v in _pending.items() if v.get("chat_id") == chat_id), None)
        if not token:
            return False
        state = _pending.pop(token)
    bot.send_message("✅ <b>Принято.</b> ИИ уточнил запрос и строит поиск…")
    _finish(state, text)
    return True


def _wrap_get_updates():
    """Intercept free-text clarification replies before the normal command loop."""
    if getattr(bot.get_updates, "_search_clarifier_wrapped", False):
        return
    original_get_updates = bot.get_updates

    def wrapped(offset=None):
        updates = original_get_updates(offset)
        kept = []
        for update in updates:
            if _consume_text(update):
                continue
            kept.append(update)
        return kept

    wrapped._search_clarifier_wrapped = True
    bot.get_updates = wrapped


def start_or_search(request, original):
    request = request.strip()
    plan = clarify(request)
    if plan.get("clarification_needed") and _ask(request, plan, original):
        return
    return original(request)


def _callback(update):
    cq = update.get("callback_query") or {}
    data = str(cq.get("data", ""))
    if not data.startswith("searchclarify:"):
        return False
    parts = data.split(":", 2)
    if len(parts) != 3:
        return True
    token, choice = parts[1], parts[2]
    with _lock:
        state = _pending.get(token)
        if not state:
            state = None
        elif choice == "custom":
            state["awaiting_custom"] = True
        else:
            _pending.pop(token, None)
    if not state:
        bot.answer_callback(cq.get("id"), "Уточнение устарело. Напиши /search заново.", alert=True)
        return True
    if choice == "custom":
        bot.answer_callback(cq.get("id"), "Напиши свой вариант сообщением")
        bot.send_message("✏️ <b>Свой ответ</b>\n\nНапиши обычным сообщением, что именно нужно искать. Я передам это ИИ как уточнение.")
        return True
    if choice == "skip":
        extra = "Ищи широко по исходному запросу."
    else:
        try:
            extra = state["values"][int(choice)]
        except Exception:
            extra = "Ищи широко по исходному запросу."
    bot.answer_callback(cq.get("id"), "Принято. ИИ строит поиск…")
    _finish(state, extra)
    return True


_wrap_get_updates()

_original = bot.handle_callback

def _handle_callback(update):
    if _callback(update):
        return
    return _original(update)

bot.handle_callback = _handle_callback
