#!/usr/bin/env python3
"""AI clarification + entity-first Telegram search planner.

Clarification is generated by the LLM. The user can select several generated
inline options, add a custom answer, or simply send a free-text answer.
Selection is kept until the user presses Done.
"""
import html
import os
import secrets
import threading
import checknow_bot as bot

_pending = {}
_lock = threading.Lock()
_LANG = {"zh":"Chinese", "en":"English", "ru":"Russian", "ja":"Japanese", "ko":"Korean"}


def _languages():
    raw = os.getenv("SEARCH_LANGUAGES", "zh,en").strip()
    return [x.strip().lower() for x in raw.split(",") if x.strip().lower() in _LANG] or ["zh", "en"]


def _call(prompt, fallback):
    if not bot.LLM_API_KEY:
        return fallback
    try:
        data = bot.call_model(bot.MODELS[0], prompt)
        return data if isinstance(data, dict) else fallback
    except Exception as e:
        print(f"search AI fallback: {e}", flush=True)
        return fallback


def clarify(request):
    langs = ", ".join(_LANG[x] for x in _languages())
    prompt = f'''You are an intelligent clarification agent for a Telegram historical search.
User request: {request}
Search languages: {langs}.
Do NOT create search queries yet.

Decide whether one clarification question would materially improve THIS search.
Ask only when the request genuinely has multiple plausible interpretations, an important missing scope, or an ambiguous target. If it is already clear, return clarification_needed=false.

If clarification is needed:
- Generate EXACTLY ONE useful question from the user's request.
- Generate 2-5 concise answer options that are specific to THIS request, not generic canned choices.
- The user may select MULTIPLE options at once, so make options independent dimensions/aspects rather than mutually exclusive answers.
- Options are suggestions, not the only possible answers.
- Do NOT include a "Свой ответ" option; the bot adds it itself.

Return strict JSON only:
{{"clarification_needed":true,"question":"...","options":[{{"label":"...","value":"..."}}]}}
or
{{"clarification_needed":false}}'''
    data = _call(prompt, {"clarification_needed": False})
    options = []
    for x in data.get("options", []):
        if isinstance(x, dict):
            label = str(x.get("label", "")).strip()[:48]
            value = str(x.get("value", "")).strip()[:300]
            if label and value:
                options.append({"label": label, "value": value})
    return {
        "clarification_needed": bool(data.get("clarification_needed")) and bool(str(data.get("question", "")).strip()) and bool(options),
        "question": str(data.get("question", "")).strip()[:700],
        "options": options[:5],
    }


def plan_search(request):
    """Generate entity-first queries without artificial Cartesian-product noise."""
    if not bot.LLM_API_KEY:
        return {"queries": [request], "intent": request}
    langs = ", ".join(_LANG[x] for x in _languages())
    prompt = f'''You are a Telegram search-query planner.
User request: {request}
Allowed languages: {langs}. If Russian is not listed, NEVER output Russian.

Extract the concrete entities/topics the user wants searched. Do not invent unrelated search intents.

RULES:
1. EVERY important named entity MUST appear ALONE first: stripe, cursor, python, tiktok, tik tok, etc.
2. Add genuine spelling variants separately, especially "tiktok" and "tik tok".
3. Add only directly useful short combinations explicitly implied by the request, such as: stripe python, cursor python, tiktok api, tik tok api, tiktok username, tik tok username, tiktok abuse, tik tok abuse.
4. Never create a Cartesian product of every entity and every modifier.
5. Do NOT invent words such as hack, exploit, bypass, attack, vulnerability, spam, flood, manipulation, injection, automation, code, script, tutorial, example, github, loop, requests, etc. unless the user explicitly asked for that concept.
6. If the user said "abuse", "abuse" is allowed. Do not turn it into ten synonyms.
7. Keep one-term entity queries; they are intentionally broad and important.
8. Search languages must be zh/en by default. Never translate the whole Russian request into search phrases.
9. Chinese queries must be natural Chinese. Keep common English brand names where appropriate.
10. Queries should normally contain 1-3 terms. No artificial maximum count: return every genuinely useful short entity/variant/combo, but do not pad.

GOOD EXAMPLE:
stripe
cursor
python
stripe python
cursor python
tiktok
tik tok
抖音
tiktok api
tik tok api
tiktok username
tik tok username
tiktok abuse
tik tok abuse

BAD EXAMPLE:
python cursor flood
python cursor attack
cursor manipulation
stripe python requests

Return strict JSON: {{"queries":[...],"intent":"..."}}'''
    data = _call(prompt, {"queries": [request], "intent": request})
    queries, seen = [], set()
    for raw in data.get("queries", []):
        q = str(raw).strip()
        if not q or len(q) > 80 or len(q.split()) > 3:
            continue
        k = q.casefold()
        if k not in seen:
            seen.add(k)
            queries.append(q)
    return {"queries": queries or [request], "intent": str(data.get("intent", request))[:1000]}


def _markup(token, state):
    rows = []
    selected = state.get("selected", set())
    for i, item in enumerate(state["options"]):
        mark = "☑️" if i in selected else "☐"
        rows.append([{"text": f"{mark} {item['label']}", "callback_data": f"searchclarify:{token}:pick:{i}"}])
    rows.append([{"text": "✏️ Свой ответ", "callback_data": f"searchclarify:{token}:custom"}])
    rows.append([{"text": "🚀 Искать без уточнения", "callback_data": f"searchclarify:{token}:skip"}])
    if selected or state.get("custom_answers"):
        rows.append([{"text": "✅ Готово", "callback_data": f"searchclarify:{token}:done"}])
    return bot.kb(rows)


def _selection_text(state):
    selected = [state["options"][i]["value"] for i in sorted(state.get("selected", set()))]
    selected += state.get("custom_answers", [])
    return "\n".join(f"• {html.escape(x)}" for x in selected)


def _ask(request, plan, original):
    token = secrets.token_urlsafe(8)
    values = [item["value"] for item in plan.get("options", [])]
    with _lock:
        _pending[token] = {
            "request": request,
            "values": values,
            "options": plan.get("options", []),
            "original": original,
            "chat_id": str(bot.CHAT_ID),
            "selected": set(),
            "custom_answers": [],
            "awaiting_custom": False,
            "message_id": None,
            "question": plan["question"],
        }
    state = _pending[token]
    sent = bot.send_message(
        "❓ <b>ИИ хочет уточнить запрос</b>\n\n"
        + html.escape(plan["question"])
        + "\n\n<i>Можно выбрать несколько вариантов. После выбора нажми «Готово» или просто напиши свой ответ.</i>",
        _markup(token, state),
    )
    try:
        mid = (sent.get("result") or {}).get("message_id")
        with _lock:
            if token in _pending:
                _pending[token]["message_id"] = mid
    except Exception:
        pass
    return True


def _finish(state, extra):
    parts = []
    selected = [state["values"][i] for i in sorted(state.get("selected", set()))]
    parts.extend(selected)
    parts.extend(state.get("custom_answers", []))
    if extra:
        parts.append(extra)
    unique = []
    seen = set()
    for x in parts:
        k = x.casefold()
        if k not in seen:
            seen.add(k)
            unique.append(x)
    clarification = "\n".join(f"• {x}" for x in unique) or "Ищи широко по исходному запросу."
    request = state["request"] + "\n\n[УТОЧНЕНИЕ ПОЛЬЗОВАТЕЛЯ]\n" + clarification
    threading.Thread(target=state["original"], args=(request,), daemon=True).start()


def _consume_text(update):
    """A normal text message is a free-text answer and finishes the clarification."""
    message = update.get("message") or {}
    chat_id = str((message.get("chat") or {}).get("id", ""))
    text = str(message.get("text") or "").strip()
    if not text or chat_id != str(bot.CHAT_ID) or text.startswith("/"):
        return False
    with _lock:
        token = next((k for k, v in _pending.items() if v.get("chat_id") == chat_id), None)
        if not token:
            return False
        state = _pending.pop(token)
    bot.send_message("✅ <b>Принято.</b> ИИ учитывает твой ответ и строит поиск…")
    _finish(state, text)
    return True


def _wrap_get_updates():
    """Intercept free-text clarification replies before the normal command loop."""
    if getattr(bot.get_updates, "_search_clarifier_wrapped", False):
        return
    original_get_updates = bot.get_updates

    def wrapped(offset=None):
        updates = original_get_updates(offset)
        kept = []
        for update in updates:
            if _consume_text(update):
                continue
            kept.append(update)
        return kept

    wrapped._search_clarifier_wrapped = True
    bot.get_updates = wrapped


def start_or_search(request, original):
    request = request.strip()
    plan = clarify(request)
    if plan.get("clarification_needed") and _ask(request, plan, original):
        return
    return original(request)


def _callback(update):
    cq = update.get("callback_query") or {}
    data = str(cq.get("data", ""))
    if not data.startswith("searchclarify:"):
        return False
    parts = data.split(":")
    if len(parts) < 3:
        return True
    token = parts[1]
    choice = parts[2]
    with _lock:
        state = _pending.get(token)
        if not state:
            state = None
        elif choice == "pick" and len(parts) >= 4:
            try:
                idx = int(parts[3])
                if 0 <= idx < len(state["values"]):
                    if idx in state["selected"]:
                        state["selected"].remove(idx)
                    else:
                        state["selected"].add(idx)
            except Exception:
                pass
        elif choice == "custom":
            state["awaiting_custom"] = True
        elif choice == "done":
            if not state.get("selected") and not state.get("custom_answers"):
                state = None
            else:
                _pending.pop(token, None)
        elif choice == "skip":
            _pending.pop(token, None)
    if not state:
        bot.answer_callback(cq.get("id"), "Уточнение устарело или ничего не выбрано.", alert=True)
        return True
    if choice == "pick":
        bot.answer_callback(cq.get("id"), "Выбрано. Можно выбрать ещё.")
        mid = (cq.get("message") or {}).get("message_id")
        try:
            bot.edit_message(mid, "❓ <b>ИИ хочет уточнить запрос</b>\n\n" + html.escape(state["question"]) + "\n\n<b>Выбрано:</b>\n" + (_selection_text(state) or "—"), _markup(token, state))
        except Exception as e:
            print(f"clarification edit: {e}", flush=True)
        return True
    if choice == "custom":
        bot.answer_callback(cq.get("id"), "Напиши свой вариант сообщением")
        bot.send_message("✏️ <b>Свой ответ</b>\n\nНапиши уточнение обычным сообщением. Его можно будет сочетать с выбранными кнопками.")
        return True
    if choice == "done":
        bot.answer_callback(cq.get("id"), "Принято. ИИ строит поиск…")
        _finish(state, "")
        return True
    if choice == "skip":
        bot.answer_callback(cq.get("id"), "Ищу без уточнения…")
        _finish(state, "Ищи широко по исходному запросу.")
        return True
    return True


_wrap_get_updates()

_original = bot.handle_callback

def _handle_callback(update):
    if _callback(update):
        return
    return _original(update)

bot.handle_callback = _handle_callback
