#!/usr/bin/env python3
"""AI clarification layer for Telegram Search.

The LLM decides whether the user's request is ambiguous enough to warrant a
question. The question and inline choices are generated by the LLM itself.
"""
import html
import secrets
import threading
import os

import checknow_bot as bot

_pending = {}
_lock = threading.Lock()


def _languages():
    raw = os.getenv("SEARCH_LANGUAGES", "zh,en").strip()
    allowed = {"zh": "Chinese", "en": "English", "ru": "Russian", "ja": "Japanese", "ko": "Korean"}
    return [x.strip().lower() for x in raw.split(",") if x.strip().lower() in allowed] or ["zh", "en"]


def _ai_clarify(request):
    if not bot.LLM_API_KEY:
        return {"clarification_needed": False}
    langs = ", ".join({"zh":"Chinese", "en":"English", "ru":"Russian", "ja":"Japanese", "ko":"Korean"}[x] for x in _languages())
    prompt = f'''You are the clarification agent for a Telegram historical-search bot.
User request:
{request}

Search languages: {langs}.
Do NOT search yet. Decide whether one human clarification would materially improve
this particular search. If the request has multiple plausible targets, unclear
scope, or an ambiguous important term, ASK ONE SPECIFIC QUESTION about THIS exact
request. The question must be generated from the request, not selected from a
hard-coded template. Generate 2-5 concise answer buttons yourself; the final
button must be "🔎 Всё" meaning the broadest interpretation.
If the request is already clear enough, return clarification_needed=false.

Return strict JSON only:
{{"clarification_needed":true,"question":"...","options":[{{"label":"...","value":"..."}}]}}
OR {{"clarification_needed":false}}'''
    try:
        data = bot.call_model(bot.MODELS[0], prompt)
        if not isinstance(data, dict):
            return {"clarification_needed": False}
        options = []
        for item in data.get("options", []):
            if isinstance(item, dict):
                label = str(item.get("label", "")).strip()[:48]
                value = str(item.get("value", "")).strip()[:300]
                if label and value:
                    options.append({"label": label, "value": value})
        question = str(data.get("question", "")).strip()[:700]
        return {"clarification_needed": bool(data.get("clarification_needed")) and bool(question) and bool(options), "question": question, "options": options[:5]}
    except Exception as e:
        print(f"AI clarification fallback: {e}", flush=True)
        return {"clarification_needed": False}


def _ask(request, plan, original):
    token = secrets.token_urlsafe(8)
    buttons = []
    values = []
    for item in plan.get("options", []):
        values.append(item["value"])
        buttons.append({"text": item["label"], "callback_data": f"searchclarify:{token}:{len(values)-1}"})
    if not buttons:
        return False
    with _lock:
        _pending[token] = {"request": request, "values": values, "original": original}
    rows = [buttons[i:i + 2] for i in range(0, len(buttons), 2)]
    rows.append([{"text": "🚀 Искать без уточнения", "callback_data": f"searchclarify:{token}:skip"}])
    bot.send_message("❓ <b>ИИ хочет уточнить запрос</b>\n\n" + html.escape(plan["question"]), bot.kb(rows))
    return True


def start_or_search(request, original):
    request = request.strip()
    plan = _ai_clarify(request)
    if plan.get("clarification_needed") and _ask(request, plan, original):
        bot.send_message("🧠 Поиск пока не запущен. После ответа ИИ заново построит поисковые фразы с учётом уточнения.")
        return
    return original(request)


def _callback(update):
    cq = update.get("callback_query") or {}
    data = str(cq.get("data", ""))
    if not data.startswith("searchclarify:"):
        return False
    parts = data.split(":", 2)
    if len(parts) != 3:
        return True
    token, choice = parts[1], parts[2]
    with _lock:
        state = _pending.pop(token, None)
    if not state:
        bot.answer_callback(cq.get("id"), "Уточнение устарело. Напиши /search заново.", alert=True)
        return True
    if choice == "skip":
        extra = "Пользователь не сузил поиск; используй широкую, но релевантную стратегию."
    else:
        try:
            extra = state["values"][int(choice)]
        except Exception:
            extra = "Пользователь выбрал широкий поиск."
    bot.answer_callback(cq.get("id"), "Принято. ИИ строит поиск…")
    request = state["request"] + "\n\n[УТОЧНЕНИЕ ПОЛЬЗОВАТЕЛЯ]\n" + extra
    threading.Thread(target=state["original"], args=(request,), daemon=True).start()
    return True


_original = bot.handle_callback


def _handle_callback(update):
    if _callback(update):
        return
    return _original(update)


bot.handle_callback = _handle_callback
